name: nyc_taxi
version: "1.0.0"
config-version: 2
profile: nyc_taxi

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  nyc_taxi:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
