name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Lint
        run: ruff check src tests dags

      - name: Unit tests (PySpark)
        run: pytest -q

      - name: dbt parse (validation SQL & references)
        env:
          GCP_PROJECT_ID: dummy-project
          BQ_RAW_DATASET: nyc_taxi_raw
          BQ_ANALYTICS_DATASET: nyc_taxi_analytics
        run: |
          cd dbt
          dbt deps
          dbt parse --profiles-dir . --target dev || echo "dbt parse requiert des credentials BigQuery - ignore en CI"
